project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebook/customer_segmentation_model.ipynb
      title: Customer Segmentation Notebook 
  resources: 
    - resources/Data_Dictionary.html
toc-location: right

format:
  html:
    # comments:
     # hypothesis: true
  # docx: default
  # jats: default

  # (other formats)
  pdf: default

execute:
  freeze: true



