project:
  type: website
  output-dir: docs

website:
  title: "Apex Project: Team Plotmasters"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
